"""
Automatic Report Generator for Legal NLP Research Framework.
Produces HTML, Markdown, or LaTeX reports from experiment results.
"""

import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ title }}</title>
<style>
  body { font-family: 'Georgia', serif; max-width: 1100px; margin: 0 auto; padding: 40px 20px;
         background: #fafafa; color: #1a1a2e; }
  h1 { color: #1a1a2e; border-bottom: 3px solid #4a90d9; padding-bottom: 10px; }
  h2 { color: #16213e; border-bottom: 1px solid #ddd; padding-bottom: 6px; margin-top: 40px; }
  h3 { color: #0f3460; margin-top: 25px; }
  .meta { background: #e8f4f8; padding: 12px 20px; border-radius: 6px; margin-bottom: 30px;
           font-size: 0.9em; color: #555; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 0.9em; }
  th { background: #1a1a2e; color: white; padding: 10px 14px; text-align: left; }
  td { padding: 8px 14px; border-bottom: 1px solid #eee; }
  tr:nth-child(even) { background: #f5f5f5; }
  .metric-card { display: inline-block; background: white; border: 1px solid #ddd;
                 border-radius: 8px; padding: 16px 24px; margin: 8px;
                 min-width: 160px; text-align: center; box-shadow: 0 2px 4px rgba(0,0,0,0.08); }
  .metric-value { font-size: 2em; font-weight: bold; color: #4a90d9; }
  .metric-label { font-size: 0.8em; color: #888; text-transform: uppercase; letter-spacing: 1px; }
  .figure { text-align: center; margin: 20px 0; }
  .figure img { max-width: 100%; border: 1px solid #eee; border-radius: 4px; }
  .figure-caption { font-size: 0.85em; color: #666; margin-top: 8px; }
  .hypothesis { background: #fff8e1; border-left: 4px solid #ffc107; padding: 12px 16px;
                margin: 12px 0; border-radius: 0 6px 6px 0; }
  .hypothesis.supported { border-color: #4caf50; background: #f1f8e9; }
  .hypothesis.partial { border-color: #ff9800; background: #fff3e0; }
  .finding { background: #e3f2fd; border-left: 4px solid #2196f3; padding: 12px 16px;
             margin: 12px 0; border-radius: 0 6px 6px 0; }
  code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }
  .toc { background: #fff; border: 1px solid #ddd; padding: 16px 24px; border-radius: 6px;
         margin-bottom: 30px; }
  .toc ul { margin: 0; padding-left: 20px; }
  .toc li { margin: 4px 0; }
  footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #eee;
           font-size: 0.8em; color: #999; text-align: center; }
</style>
</head>
<body>
{{ content }}
<footer>Generated by Spike-Legal-NLP Research Framework &bull; {{ timestamp }}</footer>
</body>
</html>"""


class ReportGenerator:
    """
    Generates comprehensive research reports from experiment results.
    Supports HTML (primary), Markdown, and LaTeX output formats.
    """

    def __init__(self, config: dict):
        self.config = config
        rep_cfg = config.get("reporting", {})
        self.fmt = rep_cfg.get("format", "html")
        self.include_figures = rep_cfg.get("include_figures", True)
        self.include_tables = rep_cfg.get("include_tables", True)
        self.out_dir = Path(config.get("storage", {}).get("reports", "storage/results/reports"))
        self.out_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        title: str,
        experiment_config: dict,
        classification_results: Optional[dict] = None,
        semantic_results: Optional[dict] = None,
        energy_results: Optional[dict] = None,
        domain_shift_results: Optional[dict] = None,
        dataset_stats: Optional[dict] = None,
        figure_paths: Optional[list[str]] = None,
        raw_results: Optional[dict] = None,
        filename: Optional[str] = None,
    ) -> str:
        """
        Generate a complete experiment report.

        Returns:
            path to the generated report file
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        fname = filename or f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

        if self.fmt == "html":
            content = self._build_html(
                title, timestamp, experiment_config,
                classification_results, semantic_results, energy_results,
                domain_shift_results, dataset_stats, figure_paths, raw_results,
            )
            path = self.out_dir / f"{fname}.html"
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
        elif self.fmt == "markdown":
            content = self._build_markdown(
                title, timestamp, experiment_config,
                classification_results, semantic_results, energy_results,
                domain_shift_results, dataset_stats, raw_results,
            )
            path = self.out_dir / f"{fname}.md"
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
        elif self.fmt == "latex":
            content = self._build_latex(
                title, timestamp,
                classification_results, semantic_results, energy_results,
                domain_shift_results,
            )
            path = self.out_dir / f"{fname}.tex"
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
        else:
            raise ValueError(f"Unknown report format: {self.fmt}")

        # Always save raw JSON alongside
        json_path = self.out_dir / f"{fname}_raw.json"
        with open(json_path, "w") as f:
            json.dump(
                {
                    "title": title,
                    "timestamp": timestamp,
                    "classification": classification_results,
                    "semantic": semantic_results,
                    "energy": energy_results,
                    "domain_shift": domain_shift_results,
                },
                f, indent=2, default=str,
            )

        logger.info(f"Report generated → {path}")
        logger.info(f"Raw JSON → {json_path}")
        return str(path)

    # ─────────────────────────────────────────────────────────────────
    # HTML Builder
    # ─────────────────────────────────────────────────────────────────

    def _build_html(
        self, title, timestamp, config,
        clf_results, sem_results, energy_results, shift_results, ds_stats,
        figure_paths, raw_results,
    ) -> str:
        sections = []
        sections.append(f"<h1>{title}</h1>")
        sections.append(
            f'<div class="meta">'
            f"Generated: {timestamp} &bull; "
            f"Framework: Spike-Legal-NLP v1.0"
            f"</div>"
        )

        # TOC
        toc_items = []
        if ds_stats:
            toc_items.append('<li><a href="#dataset">Dataset Statistics</a></li>')
        if clf_results:
            toc_items.append('<li><a href="#classification">Classification Results</a></li>')
        if sem_results:
            toc_items.append('<li><a href="#semantic">Semantic Preservation</a></li>')
        if energy_results:
            toc_items.append('<li><a href="#energy">Energy Analysis</a></li>')
        if shift_results:
            toc_items.append('<li><a href="#domain">Domain Shift</a></li>')
        if figure_paths:
            toc_items.append('<li><a href="#figures">Figures</a></li>')
        toc_items.append('<li><a href="#hypotheses">Hypothesis Evaluation</a></li>')

        sections.append(
            f'<div class="toc"><h3>Contents</h3><ul>{"".join(toc_items)}</ul></div>'
        )

        # Abstract
        sections.append("<h2>Research Overview</h2>")
        sections.append(
            "<p>This report presents results from the <em>Spike Encoding for Legal Text "
            "Classification</em> research framework. The study compares transformer-based "
            "baselines (LegalBERT, BERT) with spiking neural networks (SNNs) using five "
            "spike encoding strategies, evaluated on legal NLP datasets from LexGLUE.</p>"
        )

        # Experiment config summary
        sections.append("<h3>Experiment Configuration</h3>")
        sections.append("<table><tr><th>Parameter</th><th>Value</th></tr>")
        enc_cfg = config.get("encoding", {})
        snn_cfg = config.get("snn", {})
        params = [
            ("Time Steps", enc_cfg.get("time_steps", "—")),
            ("SNN Hidden Size", snn_cfg.get("architecture", {}).get("hidden_size", "—")),
            ("SNN Epochs", snn_cfg.get("training", {}).get("num_epochs", "—")),
            ("SNN Beta (LIF)", snn_cfg.get("neuron", {}).get("beta", "—")),
            ("Max Sequence Length", config.get("preprocessing", {}).get("max_length", "—")),
        ]
        for k, v in params:
            sections.append(f"<tr><td>{k}</td><td><code>{v}</code></td></tr>")
        sections.append("</table>")

        # Dataset Statistics
        if ds_stats:
            sections.append('<h2 id="dataset">Dataset Statistics</h2>')
            for ds_name, stats in ds_stats.items():
                sections.append(f"<h3>{ds_name}</h3>")
                sections.append("<table><tr><th>Split</th><th>Samples</th>"
                               "<th>Classes</th><th>Avg Tokens</th><th>Max Tokens</th>"
                               "<th>>512 tokens</th></tr>")
                for split_name, sp in stats.get("splits", {}).items():
                    sections.append(
                        f"<tr><td>{split_name}</td>"
                        f"<td>{sp.get('n_samples', '—')}</td>"
                        f"<td>{sp.get('n_classes', '—')}</td>"
                        f"<td>{sp.get('token_stats', {}).get('mean', 0):.0f}</td>"
                        f"<td>{sp.get('token_stats', {}).get('max', 0)}</td>"
                        f"<td>{sp.get('token_stats', {}).get('pct_over_512', 0):.1%}</td>"
                        f"</tr>"
                    )
                sections.append("</table>")

        # Classification Results
        if clf_results:
            sections.append('<h2 id="classification">Classification Results</h2>')
            sections.append(
                '<div class="finding">These results compare transformer-based linear probes '
                "with SNN classifiers trained on spike-encoded embeddings.</div>"
            )
            sections.append(
                "<table><tr><th>Model / Encoding</th><th>Accuracy</th>"
                "<th>F1 Macro</th><th>F1 Micro</th></tr>"
            )
            for name, res in clf_results.items():
                if isinstance(res, dict):
                    acc = res.get("accuracy", res.get("final_val", {}).get("accuracy", "—"))
                    f1m = res.get("f1_macro", res.get("final_val", {}).get("f1_macro", "—"))
                    f1i = res.get("f1_micro", res.get("final_val", {}).get("f1_micro", "—"))
                    sections.append(
                        f"<tr><td><code>{name}</code></td>"
                        f"<td>{_fmt_pct(acc)}</td>"
                        f"<td>{_fmt_pct(f1m)}</td>"
                        f"<td>{_fmt_pct(f1i)}</td></tr>"
                    )
            sections.append("</table>")

        # Semantic Preservation
        if sem_results:
            sections.append('<h2 id="semantic">Semantic Preservation Analysis</h2>')
            sections.append(
                '<div class="finding">Measures how well spike encodings preserve the '
                "semantic geometry of the original transformer embeddings.</div>"
            )
            sections.append(
                "<table><tr><th>Encoding</th><th>Cosine Similarity</th>"
                "<th>Spearman ρ</th><th>Kendall τ</th><th>Top-10 NN</th></tr>"
            )
            for enc, res in sem_results.items():
                sections.append(
                    f"<tr><td><code>{enc}</code></td>"
                    f"<td>{_fmt_float(res.get('mean_cosine_similarity'))}</td>"
                    f"<td>{_fmt_float(res.get('spearman_rho'))}</td>"
                    f"<td>{_fmt_float(res.get('kendall_tau'))}</td>"
                    f"<td>{_fmt_pct(res.get('topk_nn_overlap_k10'))}</td></tr>"
                )
            sections.append("</table>")

        # Energy Analysis
        if energy_results:
            sections.append('<h2 id="energy">Energy Analysis</h2>')
            sections.append(
                '<div class="finding">Energy estimates based on Horowitz (2014): '
                "4.6 pJ/MAC (GPU), 0.9 pJ/SOP (neuromorphic), 100 pJ/DRAM-access.</div>"
            )
            # Summary cards
            sections.append('<div style="margin:20px 0">')
            for enc, er in energy_results.items():
                comp = er["comparison"]
                sections.append(
                    f'<div class="metric-card">'
                    f'<div class="metric-value">{comp["energy_ratio"]:.1f}×</div>'
                    f'<div class="metric-label">{enc.replace("_", " ")}<br>efficiency</div>'
                    f"</div>"
                )
            sections.append("</div>")
            sections.append(
                "<table><tr><th>Encoding</th><th>SNN Compute (µJ)</th>"
                "<th>SNN Memory (µJ)</th><th>SNN Total (µJ)</th>"
                "<th>vs Transformer</th><th>Sparsity</th></tr>"
            )
            for enc, er in energy_results.items():
                snn_e = er["snn_energy"]
                comp = er["comparison"]
                sections.append(
                    f"<tr><td><code>{enc}</code></td>"
                    f"<td>{snn_e['compute_energy_pj']/1e6:.4f}</td>"
                    f"<td>{snn_e['memory_energy_pj']/1e6:.4f}</td>"
                    f"<td>{snn_e['total_energy_pj']/1e6:.4f}</td>"
                    f"<td>−{comp['energy_savings_pct']:.1f}%</td>"
                    f"<td>{snn_e['sparsity']:.1%}</td></tr>"
                )
            # Transformer row
            first_er = list(energy_results.values())[0]
            t_e = first_er["transformer_energy"]
            sections.append(
                f"<tr style='font-weight:bold'><td>Transformer (baseline)</td>"
                f"<td>{t_e['compute_energy_pj']/1e6:.4f}</td>"
                f"<td>{t_e['memory_energy_pj']/1e6:.4f}</td>"
                f"<td>{t_e['total_energy_pj']/1e6:.4f}</td>"
                f"<td>—</td><td>—</td></tr>"
            )
            sections.append("</table>")

        # Domain Shift
        if shift_results:
            sections.append('<h2 id="domain">Domain Shift Evaluation</h2>')
            model_keys = [k for k in shift_results if not k.startswith("_")]
            ranking = shift_results.get("_ranking_by_robustness", model_keys)
            sections.append(
                f"<p>Models ranked by robustness (lowest accuracy drop): "
                f"<strong>{' &gt; '.join(ranking)}</strong></p>"
            )
            sections.append(
                "<table><tr><th>Model</th><th>Avg Accuracy Drop</th>"
                "<th>Avg Target Acc</th><th>Avg H-Score</th></tr>"
            )
            for model in model_keys:
                r = shift_results[model]
                sections.append(
                    f"<tr><td><code>{model}</code></td>"
                    f"<td>{r.get('avg_accuracy_drop', 0):.4f}</td>"
                    f"<td>{r.get('avg_target_accuracy', 0):.4f}</td>"
                    f"<td>{r.get('avg_h_score', 0):.4f}</td></tr>"
                )
            sections.append("</table>")

        # Figures
        if figure_paths and self.include_figures:
            sections.append('<h2 id="figures">Figures</h2>')
            for fig_path in figure_paths:
                if not fig_path or not os.path.exists(fig_path):
                    continue
                path = Path(fig_path)
                rel = os.path.relpath(fig_path, self.out_dir)
                caption = path.stem.replace("_", " ").title()
                if path.suffix.lower() in (".png", ".jpg", ".jpeg"):
                    sections.append(
                        f'<div class="figure">'
                        f'<img src="{rel}" alt="{caption}">'
                        f'<div class="figure-caption">Figure: {caption}</div>'
                        f"</div>"
                    )
                else:
                    sections.append(
                        f'<div class="figure">'
                        f'<p><a href="{rel}">[PDF Figure: {caption}]</a></p>'
                        f"</div>"
                    )

        # Hypothesis Evaluation
        sections.append('<h2 id="hypotheses">Hypothesis Evaluation</h2>')
        hypotheses = self._evaluate_hypotheses(clf_results, sem_results, energy_results, shift_results)
        for hyp_id, hyp_text, verdict, evidence in hypotheses:
            cls = "supported" if verdict == "✓ Supported" else "partial" if "Partial" in verdict else ""
            sections.append(
                f'<div class="hypothesis {cls}">'
                f"<strong>{hyp_id} — {verdict}</strong><br>"
                f"{hyp_text}<br>"
                f"<em>{evidence}</em>"
                f"</div>"
            )

        content = "\n".join(sections)
        return HTML_TEMPLATE.replace("{{ title }}", title).replace("{{ content }}", content).replace("{{ timestamp }}", timestamp)

    # ─────────────────────────────────────────────────────────────────
    # Hypothesis Evaluation
    # ─────────────────────────────────────────────────────────────────

    def _evaluate_hypotheses(self, clf, sem, energy, shift) -> list[tuple]:
        results = []

        # H1: Spike encoding achieves competitive classification performance
        if clf:
            snn_results = {k: v for k, v in clf.items() if "snn" in k.lower()}
            transformer_results = {k: v for k, v in clf.items() if "transformer" in k.lower() or "bert" in k.lower()}
            if snn_results and transformer_results:
                best_snn = max(
                    (v.get("accuracy", v.get("final_val", {}).get("accuracy", 0)) for v in snn_results.values()),
                    default=0,
                )
                best_transformer = max(
                    (v.get("accuracy", 0) for v in transformer_results.values()), default=1
                )
                gap = best_transformer - best_snn
                verdict = "✓ Supported" if gap < 0.05 else "⚠ Partial" if gap < 0.15 else "✗ Not Supported"
                results.append((
                    "H1", "Spike encoding achieves competitive classification performance.",
                    verdict, f"Best SNN acc={best_snn:.4f}, Best Transformer acc={best_transformer:.4f}, gap={gap:.4f}",
                ))

        # H2: Time-based encodings preserve legal semantics better than rate coding
        if sem:
            rate_cos = sem.get("poisson_rate", {}).get("mean_cosine_similarity", 0)
            temporal_encodings = ["latency", "temporal", "population"]
            temporal_scores = [sem.get(e, {}).get("mean_cosine_similarity", 0) for e in temporal_encodings]
            best_temporal = max(temporal_scores) if temporal_scores else 0
            verdict = "✓ Supported" if best_temporal > rate_cos else "⚠ Partial" if best_temporal >= rate_cos - 0.02 else "✗ Not Supported"
            results.append((
                "H2", "Time-based encodings preserve semantics better than rate coding.",
                verdict, f"Poisson rate cos={rate_cos:.4f}, best temporal cos={best_temporal:.4f}",
            ))

        # H3: Energy improvements shrink with memory access included
        if energy:
            first = list(energy.values())[0]
            compute_ratio = first["comparison"].get("compute_only_ratio", 0)
            total_ratio = first["comparison"].get("energy_ratio", 0)
            verdict = "✓ Supported" if compute_ratio > total_ratio else "⚠ Partial"
            results.append((
                "H3", "Energy improvements exist but shrink when memory access is included.",
                verdict, f"Compute-only ratio={compute_ratio:.1f}×, total ratio={total_ratio:.1f}×",
            ))

        # H4: Domain shift affects all models differently
        if shift:
            model_keys = [k for k in shift if not k.startswith("_")]
            if len(model_keys) >= 2:
                drops = [shift[m].get("avg_accuracy_drop", 0) for m in model_keys]
                variation = max(drops) - min(drops)
                verdict = "✓ Supported" if variation > 0.02 else "⚠ Partial"
                results.append((
                    "H4", "Domain shift affects all models differently.",
                    verdict, f"Accuracy drop range: {min(drops):.4f}–{max(drops):.4f} (variation={variation:.4f})",
                ))

        return results

    # ─────────────────────────────────────────────────────────────────
    # Markdown Builder
    # ─────────────────────────────────────────────────────────────────

    def _build_markdown(self, title, timestamp, config, clf, sem, energy, shift, ds_stats, raw) -> str:
        lines = [f"# {title}", f"", f"*Generated: {timestamp}*", ""]
        if clf:
            lines += ["## Classification Results", ""]
            lines += ["| Model | Accuracy | F1 Macro | F1 Micro |", "|-------|----------|----------|----------|"]
            for name, res in clf.items():
                if isinstance(res, dict):
                    acc = _fmt_pct(res.get("accuracy", res.get("final_val", {}).get("accuracy", "—")))
                    f1m = _fmt_pct(res.get("f1_macro", res.get("final_val", {}).get("f1_macro", "—")))
                    f1i = _fmt_pct(res.get("f1_micro", res.get("final_val", {}).get("f1_micro", "—")))
                    lines.append(f"| {name} | {acc} | {f1m} | {f1i} |")
            lines.append("")
        if sem:
            lines += ["## Semantic Preservation", ""]
            lines += ["| Encoding | Cosine | Spearman ρ | Kendall τ |", "|----------|--------|------------|-----------|"]
            for enc, res in sem.items():
                lines.append(
                    f"| {enc} | {_fmt_float(res.get('mean_cosine_similarity'))} "
                    f"| {_fmt_float(res.get('spearman_rho'))} "
                    f"| {_fmt_float(res.get('kendall_tau'))} |"
                )
            lines.append("")
        return "\n".join(lines)

    def _build_latex(self, title, timestamp, clf, sem, energy, shift) -> str:
        lines = [
            r"\documentclass[12pt]{article}",
            r"\usepackage{booktabs, amsmath, graphicx, hyperref}",
            r"\title{" + title.replace("_", r"\_") + "}",
            r"\date{" + timestamp + "}",
            r"\begin{document}\maketitle",
        ]
        if clf:
            lines += [
                r"\section{Classification Results}",
                r"\begin{table}[h]\centering",
                r"\begin{tabular}{lccc}\toprule",
                r"Model & Accuracy & F1 Macro & F1 Micro \\\midrule",
            ]
            for name, res in clf.items():
                if isinstance(res, dict):
                    acc = res.get("accuracy", res.get("final_val", {}).get("accuracy", 0))
                    f1m = res.get("f1_macro", res.get("final_val", {}).get("f1_macro", 0))
                    f1i = res.get("f1_micro", res.get("final_val", {}).get("f1_micro", 0))
                    safe_name = name.replace("_", r"\_")
                    lines.append(f"{safe_name} & {acc:.4f} & {f1m:.4f} & {f1i:.4f} \\\\")
            lines += [r"\bottomrule\end{tabular}", r"\caption{Classification Results}", r"\end{table}"]
        lines.append(r"\end{document}")
        return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────
# Helper functions
# ─────────────────────────────────────────────────────────────────────

def _fmt_pct(v) -> str:
    if isinstance(v, float):
        return f"{v:.4f}"
    return str(v)


def _fmt_float(v) -> str:
    if isinstance(v, float):
        return f"{v:.4f}"
    return "—"
